name: Periodic healthcheck

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * 3,4 3"

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checking the deployed url version
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://fs-p11-e20-e21.fly.dev/health
          max-attempts: 3
          retry-delay: 15s
